# Generated by Django 4.2 on 2025-06-05 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0002_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='channel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
