# Generated by Django 4.2 on 2025-06-12 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0004_chathistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chathistory',
            options={'ordering': ['-created_at']},
        ),
    ]
