# Generated by Django 4.2 on 2025-10-23 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0005_alter_chathistory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='raw_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
