# Generated by Django 4.2 on 2025-10-27 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0006_transaction_raw_date_alter_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='value_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
