# Generated by Django migration

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0007_transaction_value_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatement',
            name='bank_type',
            field=models.CharField(choices=[('AUTO', 'Auto-detect'), ('KUDA', 'Kuda Bank'), ('OPAY', 'OPay'), ('GTBANK', 'GTBank'), ('ZENITH', 'Zenith Bank'), ('ACCESS', 'Access Bank'), ('UBA', 'UBA'), ('FCMB', 'FCMB'), ('UNKNOWN', 'Unknown')], default='AUTO', max_length=20),
        ),
    ]
